name: CI to Docker Hub

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      #- name: Build and push todo-api
      #  id: docker_build_api
      #  uses: docker/build-push-action@v3
      #  with:
      #    context: todo-api/
      #    push: true
      #    tags: ${{ secrets.DOCKER_HUB_USERNAME }}/todo-api:latest

      - name: Build and push todo-web
        id: docker_build_web
        uses: docker/build-push-action@v3
        with:
          context: todo-web/
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/todo-web:latest

      #- name: Image digest todo-api
      #  run: echo ${{ steps.docker_build_api.outputs.digest }}

      - name: Image digest todo-web
        run: echo ${{ steps.docker_build_web.outputs.digest }}
