name: Todo API CI

on:
  push:
    branches:
      - main
    paths:
      - 'todo-api/**'
  workflow_dispatch:

env:
  GIN_MODE: release

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: todo-api/
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Build container
        uses: docker/build-push-action@v3
        with:
          context: todo-api/
          push: false
          tags: ${{ github.repository_owner }}/todo-api:latest
