name: Todo Web CI

on:
  push:
    branches:
      - main
    paths:
      - 'todo-web/**'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: todo-web/
          push: false
          tags: ${{ github.repository_owner }}/todo-web:latest
